### ISSUE TITLE
Knockout bindings in Monitoring UI case sensitive to API results

### ISSUE THREAD

**Issue by askheaves** [jonsequitur/Its.Log#11]
The Api returns all discovered tests in a field called .Tests from the MonitoringTestController. If you have a camel case contract resolver, then .tests is the property from that controller.

Need to either make the knockout check both cases, or configure the monitoring test controller to use the default contract resolver.

**Comment by PhillipPruett** [comment]
the[ new UI ](https://peaky.azurewebsites.net/tests)no longer uses knockout. i will re-open this issue on Peaky as i feel this may not be totally knockout specific.

**Comment by PhillipPruett** [comment]
https://github.com/PhillipPruett/Peaky/issues/17
