### ISSUE TITLE
`ToLogString()` for type nested in generic

### ISSUE THREAD

**Issue by JayBazuzi** [jonsequitur/Its.Log#18]
This test fails due to a thrown exception.

```
public class G<T>
{
    public class C
    {
        public int I { get; set; }
    }
}

[Test]
public void MyTestMethod()
{
    Formatter.RegisterForAllMembers(typeof (G<string>.C));
    new G<string>.C().ToLogString().Should()
        .Be("{{ C: I = 0 }}");
}
```

**exception**

> System.ArgumentOutOfRangeException : StartIndex cannot be less than zero.
> Parameter name: startIndex
>    at System.String.Remove(Int32 startIndex)
>    at Its.Log.Instrumentation.Formatter.<RegisterDefaults>b__14(Type type, TextWriter writer) in C:\src\Its.Log\Its.Log\Formatter.cs:line 346

**Comment by jonsequitur** [comment]
Fixed: https://github.com/jonsequitur/Its.Log/commit/a584997181ab4ee84304a0f8a6e7d50fc7ad9dee
