### ISSUE TITLE
Its.Log.Monitoring: Support tags in querystrings

### ISSUE THREAD

**Issue by jonsequitur** [jonsequitur/Its.Log#31]
* Support routing of tags via querystring
* Reflect tag querystrings in UI tag toggles
* Update tag querystrings when UI tag toggles are changed

**Comment by PhillipPruett** [comment]
this issue is partially resolved with the latest UI but could still use more polish. https://peaky.azurewebsites.net/tests?livesite=true vs https://peaky.azurewebsites.net/tests
