### ISSUE TITLE
test discovery fails due to unresolvable dependencies

### ISSUE THREAD

**Issue by jonsequitur** [jonsequitur/Its.Log#5]
For example:

* TestClass A depends on Dependency1 and has a registration for it in the test targets.
* TestClass B does not depend on Dependency1 and has no registration for it in the test targets.

When resolving all test classes during test discovery where any class valid for that URL, e.g. 
* /tests/environment/TestClassB --> 500
* /tests/environment/TestClassA --> 200
* /tests/environment --> 500

**Comment by PhillipPruett** [comment]
moving this issue over to Peaky: https://github.com/PhillipPruett/Peaky/issues/18
